### ISSUE TITLE
New keyword CONVERGE

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/OI-Imaging-JRA#13]
If the software stop because it has converge, the keyword CONVERGE should be set to true in the OUTPUT PARAM table

**Comment by GillesDuvert** [comment]
I assumed CONVERGE is always present and is set to 0 if not converged and 1 if converged.

**Comment by jsy1001** [comment]
I agree that CONVERGE should always be present. However, I think it should be a boolean.

**Comment by GillesDuvert** [comment]
done

**Comment by jsy1001** [comment]
Done for BSMEM: https://gitlab.com/jsy1001/bsmem/-/commit/defaae14bb13ca8ae4d6756b8b3df995db9f569a

**Comment by FerreolS** [comment]
Thanks.  @emmt ?

**Comment by emmt** [comment]
I assumed a boolean, hence value is 'T' (true) or 'F (false), right?

**Comment by jsy1001** [comment]
I implemented T or F for BSMEM.

**Comment by emmt** [comment]
OK thanks, I have done the same for MiRA (see https://github.com/emmt/MiRA/commit/98b1a4f63639aef076b6cb8dffd17ca8bcace12c).

**Comment by GillesDuvert** [comment]
for Wisard, it is in [47c8d1f](https://github.com/JMMC-OpenDev/wisard-ci/commit/47c8d1f768a03ca91416e4e08cbb3747d649ef5e)

**Comment by jsy1001** [comment]
CONVERGE should be added to the specification document.
